### PR TITLE
refers moment through the window object

### PR DESCRIPTION
**Pull request by qcmatsuoka**
Hi.
I'm use closure compiler and merge javascript files.
When specified strict mode in other javascript file and do not read moment.js, occurred this error.

```
PhantomJS 1.9.8 (Linux) ERROR
  ReferenceError: Can't find variable: moment
```

because PhantomJS can't resolve the variable `momnet`.
refs #8.

This PR resolve the not exist module `moment` with strict mode.

I hope you like it.
Thank you.

### CODE REVIEW

**Comment by timmipetit** [comment]
Hi, thanks for the contribution! I'm not too sure about the fix yet. Wouldn't it be somehow possible to inject momentjs as a dependency? That seems cleaner that using $window. Otherwise I would suggest doing something like `var moment = $window.moment;` instead of referencing `$window.moment` all the time.

**Comment by qcmatsuoka** [comment]
@timmipetit 

Thank you for suggestion.

> Wouldn't it be somehow possible to inject momentjs as a dependency?

I did not notice the dependent until get an error, because it is not written with `moment` in bower.json `dependencies`.

I want to resolve variable in directive, if possible.
What about the added commit?

Thanks.:smile:

**Comment by timmipetit** [comment]
Definitely looks better this way. I still think it's weird that we need `$windows` to include `moment`, but personally I don't know any better way. So we'll merge this for now.

**Comment by qcmatsuoka** [comment]
@timmipetit 

Thank you very much.:blush:

**Pull request merged**
