### PR TITLE
Allow resetting of input when model is changed to null

### PR DESCRIPTION
**Pull request by gergderkson**

### CODE REVIEW

**Comment by timmipetit** [comment]
Thanks for the pull request! Could you also add a unit-test for this behaviour?

**Comment by gergderkson** [comment]
No problem, done!

**Comment by timmipetit** [comment]
Awesome work, thanks for contributing :)

**Comment by gergderkson** [comment]
No worries, great directive! 

Is there any plans to bump the version number? Keen to add to our project via bower

**Comment by timmipetit** [comment]
Done, bumped to version 0.11.0: https://github.com/Recras/angular-jquery-timepicker/tree/0.11.0

**Comment by gergderkson** [comment]
Amazing, thanks!

**Pull request merged**
