### PR TITLE
Fix for undefined values

### PR DESCRIPTION
**Pull request by 1itvinka**
If the value is undefined show the input placeholder and do not show error message.

### CODE REVIEW

**Comment by timmipetit** [comment]
Thank you for contributing to our project! Can you explain why you would want different behaviour for `null` and `undefined`?

**Comment by 1itvinka** [comment]
For now the input have to have initial value. I would like to have such functionality: If there is no value of datepicker selected by user, the value of the model is undefined and input placeholder is shown.

**Comment by 1itvinka** [comment]
But we should check for null of course.

**Comment by timmipetit** [comment]
Yeah, I think there is no reason to have different behaviour for null and undefined in the timepicker. Could you maybe show an example where you would need your modifications? If we would want to merge your pull request, we also need some tests.

**Comment by 1itvinka** [comment]
My case is very simple: until a user himself selects the value of timepicker no value should be selected and placeholder should be displayed. In this case the value of model is undefined. It works as it should now, but there is an annoying error in console without reason. Or I don't see one. My fix just cleans this console error. In the jquery lib you can have a timepicker without initial value as you can see in the demo http://jonthornton.github.io/jquery-timepicker/.
I'll white tests if you agree to merge this fix. 
Thank you for the useful directive by the way!

**Comment by timmipetit** [comment]
That makes sense. Currently we use `null` values for that, but I think `undefined` should work as well. If you write a test-case for your code, we'll merge it :)

**Comment by 1itvinka** [comment]
Hey @timmipetit, the tests for undefined ngModel is ready. I'm sorry it took so long for me to do. I've had tons of other urgent work to complete. If anything wrong with the tests, just tell me - I'll do my best to do it the right way. Thanks!

**Comment by timmipetit** [comment]
Hey @1itvinka, awesome work, thanks for contributing to this project!

**Pull request merged**
